### ISSUE TITLE
reproducing helpers with TS

### ISSUE THREAD

**Issue by guilhermeytalo** [Racheal777/Authentication#1]
Hi, 
I had an question about implementation on this part on `useHelper.js`.

I'm using TS and i try to implement this part(code below) in TS, you had any tip for this part specifically to help me about this?
```
module.exports.generateToken = (id) =>{
// this process.env is my actual  doubt and how to pass to a TS since doesn't had an import
  return jwt.sign({id}, process.env.privateKey, {
    expiresIn: 3 * 24 * 60 * 60* 1000
  })
}
```

**Comment by RachealKuranchie** [comment]
You can create a variable PrivateKey and save the the process.env.privateKey in it. If you get a type error, you can use unknown as the type.

**Comment by guilhermeytalo** [comment]
Thanks for the help, i just changed for this `process.env.SECRET_KEY!` and it worked!
